runtime: java11
entrypoint: java -Xmx64m -jar Server-0.0.1-SNAPSHOT.jar
instance_class: F4

automatic_scaling:
  min_instances: 1
  min_idle_instances: 1

handlers:
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto